### ISSUE TITLE
Manage *active rules* not only the file(s) containing the firewall rules

### ISSUE THREAD

**Issue by sandervanburken** [sous-chefs/firewall#199]
### Cookbook version
2.6.5 (commit: be19a256a304c0df6efc370bfe60d1140f1edea0)

### Chef-client version
Chef: 14.3.37

### Platform Details
Ubuntu 16.04 (using the kitchen suite from the firewall cookbook: iptables-ubuntu-1604)

### Scenario:

Use the firewall cookbook for managing active firewall rules.

### Steps to Reproduce:

- clone firewall cookbook
- run: `kitchen converge iptables-ubuntu-1604`
- login and execute:
  - `iptables -I INPUT 13 -p tcp -m tcp -m multiport --dports 9999 -m comment --comment "unmanaged rule" -j ACCEPT`
- run: `kitchen converge iptables-ubuntu-1604`

*RESULT*: The unmanaged rule *is not* removed from the active rules on the machine.

Add the following lines to the bottom of: test/fixtures/cookbooks/firewall-test/recipes/default.rb

```ruby
firewall 'default' do
  action :flush
end
```

- run: `kitchen converge iptables-ubuntu-1604`

*RESULT*: The unmanaged rule *is* removed from the active rules on the machine.

### Expected Result:

The cookbook should manage the desired state of the *active firewall* and not only the desired state of the file(s) containing the firewall rules.

### Actual Result:

Only when the 'flush' action is used the active rules are managed. I am unsure if the 'flush' action is intended for this use case... It seems like a radical approach that might have some undesired site affects.

**Comment by universam1** [comment]
this is really a good catch
