### ISSUE TITLE
Chains managed outside of chef are clobbered

### ISSUE THREAD

**Issue by vladionescu** [sous-chefs/firewall#209]
### Cookbook version
2.7.0

### Chef-client version
Chef: 14.10.9

### Platform Details
Fedora 28

### Scenario:
When port forwarding in Docker, Docker sets up rules in the following:
- *filter FORWARD
- *filter DOCKER
- *filter DOCKER-ISOLATION
- *nat PREROUTING
- *nat POSTROUTING
- *nat OUTPUT
- *nat DOCKER

I can't seem to only manage *filter INPUT using this cookbook. If a `firewall_rule` resource is modified, on next run chef will flush all tables and install only the rules specified in its recipes, disappearing all non-chef rules like Docker's.

This breaks things and makes it impossible to coexist both the `docker` and `firewall` cookbooks on the same node.

### Expected Result:
It would be great if I could request certain chains be left alone.

For example, the fb_iptables cookbook supports this via the notion of dynamic chains: https://github.com/facebook/chef-cookbooks/tree/master/cookbooks/fb_iptables#dynamic-chains

**Comment by martinb3** [comment]
Hi there -- this cookbook is designed to provide an abstraction across ufw, iptables, firewalld, and the Windows firewall; we've made some tradeoffs to support that design, like not expecting Firewall rules to be managed both by Chef and something else and not parsing every firewall rule in every possible syntax across those implementations (and within versions).

Perhaps iptables or iptables-ng might be a better choice for your use case of wanting dynamic chains?

**Comment by vladionescu** [comment]
Didn't know about iptables-ng, thanks for that!

I was hoping to stay on firewall because iptables and iptables-ng cookbooks are not as nice to use as this one, specifically rule resources in recipes (having to use `line` instead of the nicer semantics of firewall_rule).

I'll pick iptables-ng for the time being. I think with the prevalence of virt/container systems it would be a good idea to put dynamic chains support on the wishlist 😃

**Comment by chaim1221** [comment]
So, the solution I'm looking at for this is to use my own bridge, which is basically what the Docker documentation says to do if you need (a) a name that is predictable, not `br-deadbeef42`, and (b) automatic name resolution (because you can't use the default bridge).
https://docs.docker.com/v17.09/engine/userguide/networking/default_network/build-bridges/
https://docs.docker.com/network/iptables/ @ "Prevent Docker from manipulating tables"

So basically in my Docker recipe I have
```
file '/etc/docker/daemon.json' do
  content '{
    "bridge": "silly0"
    "iptables": false,
  }
'
  mode '0755'
  owner 'root'
  group 'root'
end
```
and I'm hacking the bridge in there for now. But when I do that I can make rules for the bridge:
```
docker_rules = [
  '-P INPUT ACCEPT',
  '-P FORWARD DROP',
  '-P OUTPUT ACCEPT',
  '-N DOCKER',
  '-N DOCKER-ISOLATION-STAGE-1',
  '-N DOCKER-ISOLATION-STAGE-2',
  '-N DOCKER-USER',
  '-A FORWARD -j DOCKER-USER',
  '-A FORWARD -j DOCKER-ISOLATION-STAGE-1',
  '-A FORWARD -o silly0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT',
  '-A FORWARD -o silly0 -j DOCKER',
  '-A FORWARD -i silly0 ! -o silly0 -j ACCEPT',
  '-A FORWARD -i silly0 -o silly0 -j ACCEPT',
  '-A DOCKER -d 192.0.2.2/32 ! -i silly0 -o silly0 -p tcp -m tcp --dport 443 -j ACCEPT',
  '-A DOCKER -d 192.0.2.3/32 ! -i silly0 -o silly0 -p tcp -m tcp --dport 1433 -j ACCEPT',
  '-A DOCKER-ISOLATION-STAGE-1 -i silly0 ! -o silly0 -j DOCKER-ISOLATION-STAGE-2',
  '-A DOCKER-ISOLATION-STAGE-1 -j RETURN',
  '-A DOCKER-ISOLATION-STAGE-2 -o silly0 -j DROP',
  '-A DOCKER-ISOLATION-STAGE-2 -j RETURN',
  '-A DOCKER-USER -j RETURN'
]
```
(this is from my test because I don't actually have this next part written yet...)

So for my rules I am imagining I'll do something like

```
docker_rules.each do |rule|
  i=25
  firewall_rule 'docker_rules' do
    raw      rule
    position i
  end
  i += 1
end
```

... but I'm still putting all this together, so maybe I'll let you know how it goes.

I might try to solve this in my fork when I get some time by having like a `docker_rules 'br0' do...end` resource or something. "When I get some time" could be quite a long time so don't count on that. ;)

**Comment by Rudikza** [comment]
> So, the solution I'm looking at for this is to use my own bridge, which is basically what the Docker documentation says to do if you need (a) a name that is predictable, not `br-deadbeef42`, and (b) automatic name resolution (because you can't use the default bridge).
> https://docs.docker.com/v17.09/engine/userguide/networking/default_network/build-bridges/
> https://docs.docker.com/network/iptables/ @ "Prevent Docker from manipulating tables"
> 
> So basically in my Docker recipe I have
> 
> ```
> file '/etc/docker/daemon.json' do
>   content '{
>     "bridge": "silly0"
>     "iptables": false,
>   }
> '
>   mode '0755'
>   owner 'root'
>   group 'root'
> end
> ```
> 
> and I'm hacking the bridge in there for now. But when I do that I can make rules for the bridge:
> 
> ```
> docker_rules = [
>   '-P INPUT ACCEPT',
>   '-P FORWARD DROP',
>   '-P OUTPUT ACCEPT',
>   '-N DOCKER',
>   '-N DOCKER-ISOLATION-STAGE-1',
>   '-N DOCKER-ISOLATION-STAGE-2',
>   '-N DOCKER-USER',
>   '-A FORWARD -j DOCKER-USER',
>   '-A FORWARD -j DOCKER-ISOLATION-STAGE-1',
>   '-A FORWARD -o silly0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT',
>   '-A FORWARD -o silly0 -j DOCKER',
>   '-A FORWARD -i silly0 ! -o silly0 -j ACCEPT',
>   '-A FORWARD -i silly0 -o silly0 -j ACCEPT',
>   '-A DOCKER -d 192.0.2.2/32 ! -i silly0 -o silly0 -p tcp -m tcp --dport 443 -j ACCEPT',
>   '-A DOCKER -d 192.0.2.3/32 ! -i silly0 -o silly0 -p tcp -m tcp --dport 1433 -j ACCEPT',
>   '-A DOCKER-ISOLATION-STAGE-1 -i silly0 ! -o silly0 -j DOCKER-ISOLATION-STAGE-2',
>   '-A DOCKER-ISOLATION-STAGE-1 -j RETURN',
>   '-A DOCKER-ISOLATION-STAGE-2 -o silly0 -j DROP',
>   '-A DOCKER-ISOLATION-STAGE-2 -j RETURN',
>   '-A DOCKER-USER -j RETURN'
> ]
> ```
> 
> (this is from my test because I don't actually have this next part written yet...)
> 
> So for my rules I am imagining I'll do something like
> 
> ```
> docker_rules.each do |rule|
>   i=25
>   firewall_rule 'docker_rules' do
>     raw      rule
>     position i
>   end
>   i += 1
> end
> ```
> 
> ... but I'm still putting all this together, so maybe I'll let you know how it goes.
> 
> I might try to solve this in my fork when I get some time by having like a `docker_rules 'br0' do...end` resource or something. "When I get some time" could be quite a long time so don't count on that. ;)

I am in the same boat. Did you manage to come right?

**Comment by chaim1221** [comment]
@Rudikza My solution is working in production almost exactly as I described, _except_ I did away with the bridge.
```
# we don't want Docker to attempt to manage iptables; the rules would be overwritten
file '/etc/docker/daemon.json' do
  content '{
    "iptables": false
  }
'
  mode '0755'
  owner 'root'
  group 'root'
end
```
Therefore, all the rules use `docker0` (the default Docker bridge) instead of `silly0` (my silly example bridge).

**Comment by stissot** [comment]
On Ubuntu with iptables, the `firewall` resource is using `netfilter-persistent` to reload the rules at the end of converge, so here is the workaround I'm using to recreate the Docker chains when needed

```ruby
docker_service 'default' do
  auto_restart true
  iptables true
  action [:create, :start]
  subscribes :restart, 'service[netfilter-persistent]', :delayed
end
```
