### ISSUE TITLE
Leveraging inspec to test firewalld rules

### ISSUE THREAD

**Issue by donwlewis** [sous-chefs/firewall#213]
### Cookbook version
2.7.0

### Chef-client version
14.12.9

### Platform Details
Fedora 29 (EL)

### Scenario:
Can't use inspec `firewalld` resource to test if ports are open.  Since this seems to configure `firewalld` leveraging the `--direct` flag, and inspec is trying to see if a port is open in a specific zone.

### Steps to Reproduce:
Create a firewall rule using the `firewall_rule` resource.  Write and integration test leverage inspec with the `firewalld` resources and the `have_port_enabled_in_zone` property.

### Expected Result:
The test should pass.

### Actual Result:
The test fails.

I realize that this is probably due to the fact that there is a limitation within this cookbook itself since it seems to be trying to encompass being able to configure different firewalls in different environments, and that is not solely focused on `firewalld`.  It would just be nice to be able to leverage this cookbook to configure firewalls, and in conjunction use the testing tool that fits well in the chef ecosystem to test it.

If it seems appropriate, I can also submit a feature request in the inspec project to test ports outside of a zone.

**Comment by iammoen** [comment]
Yea I wish this was implemented too. For now I just have to define an array of those direct rules and then do:
`describe command('firewall-cmd --direct --get-all-rules') do
    firewall_expected_rules.each do |r|
      its(:stdout) { should match(r) }
    end
  end`

But I wish this made more sense when it came to inspec tests.
